Change Status Review
ethereum/ERCs pull request #129
Opened 2023-11-28 10:32 UTC by quyphandang

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2023-12-12 15:28 UTC, SamWilsn requested changes

2023-12-12 15:28 UTC, SamWilsn commented on ERCS/erc-7254.md
Please rename this file `erc-7254.md -> eip-7254.md`.

2023-12-12 15:28 UTC, SamWilsn commented on assets/erc-7254/ERC7254.sol
Assets still live in `assets/eip-7254` (our build system is a little weird :sweat_smile:)

2023-12-13 03:17 UTC, quyphandang commented on ERCS/erc-7254.md
I attempted to change the name to EIP, but the attempt failed. Consequently, I opted to reuse the old name ERC-7254.md.

2023-12-13 03:17 UTC, quyphandang commented on assets/erc-7254/ERC7254.sol
I fixed it

2024-04-15 16:22 UTC, SamWilsn approved these changes
Assuming I haven't messed up the assets stuff again, this should be good to merge as a draft.

---

You'll really want to expand your Specification section to give implementers more information to go off of, for example, you should specify when events need to be emitted.

---

You should also include/link your `IERC7254` interface in the Specification section. It'll really help readers understand what's going on.

2024-04-15 16:25 UTC, SamWilsn requested changes

2024-04-15 16:25 UTC, SamWilsn commented on ERCS/erc-7254.md
> +Needs discussion.
Ah, I didn't realize this was going into Review. You'll need to complete the Rationale and Security Considerations sections before you can merge this.

2024-06-11 00:02 UTC, closed without merging