Smart Contract Interface to implement confidentiality and legal status transparency to crypto security tokens
ethereum/ERCs pull request #143
Opened 2023-12-05 10:02 UTC by itinance

This PR suggests a Smart contract interface standard to additionally offer confidentiality and legal status transparency to crypto securities according to the German Electronic Security Act ([eWpG](https://www.gesetze-im-internet.de/ewpg/index.html))

2023-12-06 02:43 UTC, abcoathup commented on ERCS/erc-xxx.md
> +---
```suggestion
---
eip: 7570
```
Assigning next sequential EIP/ERC/RIP number.
Numbering changed to sequential from 7500 and is no longer the PR number.

Please also update the filename.

2023-12-06 02:45 UTC, abcoathup commented on ERCS/erc-xxx.md
> +title: Smart Contract Interface to implement confidentiality and legal status transparency to crypto security tokens
```suggestion
title: Security token interface for confidentiality and legal status transparency
```
Suggest a shorter title

2024-02-12 22:01 UTC, SamWilsn requested changes
You'll need to address all the issues found by `eipw` as well: https://github.com/ethereum/ERCs/actions/runs/7112458879/job/19362450600

2024-02-12 22:01 UTC, SamWilsn commented on ERCS/erc-7570.md
> +Copyright and related rights waived via CC0.
Please use the exact waiver from [the template](https://github.com/ethereum/EIPs/blob/master/eip-template.md?plain=1#L120).

2024-04-10 00:01 UTC, closed without merging