FIx solidity formula
ethereum/ERCs pull request #201
Opened 2024-01-12 16:07 UTC by RenanSouza2

This PR fixes one formula in the ERC7201, I am not one of the authors

2024-01-15 13:21 UTC, Amxx commented
I don't think this change is needed. If `id` is a string, you can call `keccak256(id)` directly.

I was able to confirm (in remix) that
```
    bytes32 public constant MAIN_STORAGE_LOCATION =
        keccak256(abi.encode(uint256(keccak256("example.main")) - 1)) & ~bytes32(uint256(0xff));
```
does compile (tested with 0.8.7)

2024-01-15 13:29 UTC, RenanSouza2 commented
> I don't think this change is needed. If `id` is a string, you can call `keccak256(id)` directly.
> 
> I was able to confirm (in remix) that
> 
> ```
> bytes32 public constant MAIN_STORAGE_LOCATION =
>     keccak256(abi.encode(uint256(keccak256("example.main")) - 1)) & ~bytes32(uint256(0xff));
> ```
> 
> does compile (tested with 0.8.7)

it works with hardcoded string like `"example.main"` but not with a variable type string memory

2024-01-15 13:51 UTC, Amxx approved these changes

2024-01-15 20:07 UTC, ernestognw approved these changes
> it works with hardcoded string like `"example.main"` but not with a variable type string memory

Yea I can confirm.

2024-03-13 19:14 UTC, SamWilsn requested changes
https://github.com/ethcatherders/EIPIP/issues/327

2024-04-03 20:46 UTC, Amxx approved these changes

2024-04-23 02:32 UTC, SamWilsn approved these changes

2024-04-23 02:32 UTC, merged