Ethereum High-Risk Transaction Surveillance Guidelines
ethereum/ERCs pull request #229
Opened 2024-01-31 07:22 UTC by Flyme10086

This ERC proposes a standardized framework for identifying, monitoring, and regulating high-risk transactions on the Ethereum network. The framework includes a set of criteria and a procedural approach for classifying transactions as high-risk based on factors such as transaction amount, frequency, associated addresses, and patterns indicative of fraudulent or illicit activities. The aim is to enhance network security and integrity, prevent illegal activities, and maintain compliance with global regulatory standards.

2024-02-01 01:20 UTC, abcoathup commented on ERCS/erc-7688.md
> +eip: 7688
```suggestion
eip: 7606
```
Assigning next sequential EIP/ERC/RIP number.
Numbering changed to sequential from 7500 and is no longer the PR number.

Please also update the filename.

2024-02-01 01:22 UTC, abcoathup commented on ERCS/erc-7688.md
> +title: Ethereum RiskWatch Guide
```suggestion
title: Transaction risk monitoring
```
Suggest using a more descriptive title.  This is an ERC so doesn't need to include the word Ethereum.

2024-02-05 18:02 UTC, lex-node commented
no, absolutely not--kill it with fire, nuke it from orbit--I don't care 

you can't have one "standardized framework" for this because every country's laws are different and they change all the time; moreover, this should never be enshrined in the protocol, which should remain credibly neutral (i.e., not following any particular country's laws or "risk" standards) 

where would you draw the line? might as well add in China's social credit score while you're at it

2024-02-05 18:19 UTC, pcfreak30 commented
Two words.

HELL. NO.

Kudos.

2024-02-05 18:25 UTC, 0xDreamWeaver commented
Eat shit

2024-02-05 23:37 UTC, ControlCplusControlV commented
if you're going to make a honeypot atleast do it on your main github coward (and if this is your main you should be ashamed lmao)

2024-02-06 01:43 UTC, pcfreak30 commented
> I think this reintroduces some of the worst aspects of the old system while creating its own new set of problems unique to the new environment.
> 
> Catering to regulators and gatekeepers (which ones?) over financial freedom of the individual undermines the purpose of building an open source financial system within distributed systems at great expense and complexity.
> 
> I think Vitalik’s proposal to use zero knowledge proofs to prove things like “I am not a North Korean hacker” can achieve some of these goals without revealing personal information or removing sovereignty from the individual.

TBH, even that is a slippery slope. That is a form of digital ID (`soul bound token`) to prove innocence, which said another way `guilty until proven innocent`. This will always be a fight, but the pragmatic or progressive view will get abused by different groups to discriminate with the tools being made available.

2024-02-06 03:13 UTC, abcoathup commented
@lex-node, @pcfreak30, @0xDreamWeaver, @ControlCplusControlV & @miller46 

For discussions on the proposed ERC please use the Eth Magicians discussions thread:
https://ethereum-magicians.org/t/ethereum-high-risk-transaction-surveillance-guidelines/18415

2024-02-07 08:03 UTC, geet-eth commented
fuck no

2024-02-21 02:07 UTC, SamWilsn requested changes
This proposal doesn't really include enough detail to be implementable, nor does it do a good job of explaining what parties would need to implement it. I can't tell if this is meant to be implemented by clients like geth, or if this is an off-chain oracle service for smart contracts.

2024-02-21 02:07 UTC, SamWilsn commented on ERCS/erc-7606.md
> +The motivation for this standard is to provide a comprehensive framework for monitoring high-risk transactions, balancing the need for ordinary users' privacy with the necessity of preventing crimina
This paragraph reads like it belongs in the Motivation section. The Rationale section should explain technical choices made within the proposal.

> Motivation: "Why do we need a shed?"
> Rationale: "Why is the shed red?"

2024-02-21 02:07 UTC, SamWilsn commented on ERCS/erc-7606.md
> +TBD
```suggestion
```

These sections are optional.

2024-02-21 02:07 UTC, SamWilsn commented on ERCS/erc-7606.md
> +The security considerations of this standard are under discussion.
```suggestion
<!-- TODO -->
```

If you use an HTML-style comment, the linter will make sure you replace it before you move to Review.

2024-02-21 02:07 UTC, SamWilsn commented on ERCS/erc-7606.md
> +description: Establishing a framework for monitoring and regulating high-risk
Your description isn't a complete sentence, nor does it really enough information that wasn't already in the title.

2024-06-27 00:01 UTC, closed without merging