ERC-6123: Move to Draft: Enlarged interface, streamlined reference implementation.
ethereum/ERCs pull request #25
Opened 2023-10-26 16:39 UTC by cfries

This pull request will make some additions to the ERC-6123 interface, streamlined the reference implementation and improved the documentation.
Run unit test via npm install; npm test

2023-11-27 17:13 UTC, SamWilsn commented
I *think* if you rebase this, it'll pass the link checker.

2023-11-27 21:07 UTC, cfries commented
> I _think_ if you rebase this, it'll pass the link checker.

There appear to be link errors in other ERCs - not in this one:

```
For the Images check, the following failures were found:
* At ./_site/EIPS/eip-6358.html:226:
  internal image ../assets/erc-6358/img/o-dlt.png does not exist
* At ./_site/EIPS/eip-7439.html:365:
  internal image ../assets/erc-7439/normal.png does not exist
* At ./_site/EIPS/eip-7439.html:369:
  internal image ../assets/erc-7439/void.png does not exist```

I proposed to fix them here: https://github.com/ethereum/ERCs/pull/28 - but I assume it was decided to use another aproach. 

How can I move this EIP towards being merged? Its open since Oct 26. If I can be of any help, let me know.

2023-11-27 22:09 UTC, cfries commented
> I _think_ if you rebase this, it'll pass the link checker.

Thank you. Looks good now.

2023-11-28 15:32 UTC, cfries commented on ERCS/erc-6123.md
> +Note: The previous draft version of interface (used in the 2022 test trade) is `@finmath.net/sdc@0.2.3`.
Done.

2023-11-30 18:40 UTC, SamWilsn requested changes
I missed this external link on my last review. Sorry about that. You'll need to remove it, and any others, before we can merge.

2023-11-30 18:40 UTC, SamWilsn commented on ERCS/erc-6123.md
> +#### Trade Initiation Phase: inceptTrade
```suggestion
#### Trade Initiation Phase: `inceptTrade`
```

2023-11-30 18:40 UTC, SamWilsn commented on ERCS/erc-6123.md
>  ```js
````suggestion
```solidity
````

2023-11-30 18:40 UTC, SamWilsn commented on ERCS/erc-6123.md
> +- Java-based state machine and contract implementations are also available. See the finmath-smart-derivative-contract GitHub repo..
Please remove this external link.

```suggestion
```

2023-12-07 16:49 UTC, SamWilsn approved these changes

2023-12-11 21:55 UTC, merged