Website: Multi-Fungible Token
ethereum/ERCs pull request #277
Opened 2024-02-23 12:37 UTC by wluisw

Add ERC-7635 Multi-Fungible Token

2024-02-23 21:43 UTC, abcoathup commented on ERCS/erc-8000.md
> +eip: 8000
```suggestion
eip: 7635
```
Assigning next sequential EIP/ERC/RIP number.
Numbering changed to sequential from 7500.

Please also update the filename.

2024-05-24 12:38 UTC, SamWilsn commented on ERCS/erc-7635.md
> +or investment contracts, and loyalty points（KEY） from a bank. Alternatively, a game character may possess fungible
Is there a reason to use [fullwidth left parenthesis](https://www.fileformat.info/info/unicode/char/ff08/index.htm) instead of just a regular one?

2024-05-24 12:38 UTC, SamWilsn commented on ERCS/erc-7635.md
> +interface ERC165 {
Don't duplicate the interface here. Just refer to the ERC instead.

2024-05-24 12:38 UTC, SamWilsn commented on ERCS/erc-7635.md
> +interface IERC721 is IERC165 {
Don't duplicate this one either.

2024-05-24 12:43 UTC, SamWilsn requested changes

2024-05-24 12:43 UTC, SamWilsn commented on ERCS/erc-7635.md
> +The **metadata extension** is OPTIONAL for [ERC-721](./eip-721.md) smart contracts . This allows your smart
Copy-paste error?

2024-05-24 12:43 UTC, SamWilsn commented on ERCS/erc-7635.md
> +    * MUST emit `TransferValue` event.
These bullets all introduce requirements, and so should be in the specification section.

2024-05-24 12:43 UTC, SamWilsn commented on ERCS/erc-7635.md
> +
```suggestion
```


Please remove this section, or link to the one in the `assets/` directory.

2024-05-24 12:43 UTC, SamWilsn commented on assets/erc-7635/contracts/ERC7635.sol
> +// SPDX-License-Identifier: GPL-3.0-or-later
We prefer `CC0-1.0` for reference implementations, but allow most permissive non-copyleft licenses (so `MIT` is fine, but `GPL` is not.)

If you have the authority to re-license this code, could you change it to `CC0-1.0` or some other non-copyleft option?

2024-05-24 12:43 UTC, SamWilsn commented on assets/erc-7635/contracts/TestERC20.sol
> +// SPDX-License-Identifier: GPL-3.0-or-later
We prefer `CC0-1.0` for reference implementations, but allow most permissive non-copyleft licenses (so `MIT` is fine, but `GPL` is not.)

If you have the authority to re-license this code, could you change it to `CC0-1.0` or some other non-copyleft option?

2024-05-24 12:43 UTC, SamWilsn commented on assets/erc-7635/contracts/TestERC721.sol
> +// SPDX-License-Identifier: GPL-3.0-or-later
We prefer `CC0-1.0` for reference implementations, but allow most permissive non-copyleft licenses (so `MIT` is fine, but `GPL` is not.)

If you have the authority to re-license this code, could you change it to `CC0-1.0` or some other non-copyleft option?

2024-05-24 12:43 UTC, SamWilsn commented on assets/erc-7635/contracts/TestERC7635.sol
> +// SPDX-License-Identifier: GPL-3.0-or-later
We prefer `CC0-1.0` for reference implementations, but allow most permissive non-copyleft licenses (so `MIT` is fine, but `GPL` is not.)

If you have the authority to re-license this code, could you change it to `CC0-1.0` or some other non-copyleft option?

2024-05-24 12:43 UTC, SamWilsn commented on assets/erc-7635/contracts/extensions/IERC7635Metadata.sol
> +// SPDX-License-Identifier: GPL-3.0-or-later
We prefer `CC0-1.0` for reference implementations, but allow most permissive non-copyleft licenses (so `MIT` is fine, but `GPL` is not.)

If you have the authority to re-license this code, could you change it to `CC0-1.0` or some other non-copyleft option?

2024-05-24 12:43 UTC, SamWilsn commented on assets/erc-7635/contracts/interfaces/IERC721Receiver.sol
> +// SPDX-License-Identifier: GPL-3.0-or-later
We prefer `CC0-1.0` for reference implementations, but allow most permissive non-copyleft licenses (so `MIT` is fine, but `GPL` is not.)

If you have the authority to re-license this code, could you change it to `CC0-1.0` or some other non-copyleft option?

2024-05-24 12:43 UTC, SamWilsn commented on assets/erc-7635/contracts/interfaces/IERC7635.sol
> +// SPDX-License-Identifier: GPL-3.0-or-later
We prefer `CC0-1.0` for reference implementations, but allow most permissive non-copyleft licenses (so `MIT` is fine, but `GPL` is not.)

If you have the authority to re-license this code, could you change it to `CC0-1.0` or some other non-copyleft option?

2024-05-24 12:43 UTC, SamWilsn commented on assets/erc-7635/contracts/libs/TransferHelper.sol
> +// SPDX-License-Identifier: GPL-3.0-or-later
We prefer `CC0-1.0` for reference implementations, but allow most permissive non-copyleft licenses (so `MIT` is fine, but `GPL` is not.)

If you have the authority to re-license this code, could you change it to `CC0-1.0` or some other non-copyleft option?

2025-01-31 00:02 UTC, closed without merging