add Request Method Types
ethereum/ERCs pull request #315
Opened 2024-03-13 02:32 UTC by HelloRickey

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2024-03-13 23:37 UTC, abcoathup commented on ERCS/erc-xxxx.md
> +eip: xxxx
```suggestion
eip: 7654
```
Assigning next sequential EIP/ERC/RIP number.
Numbering changed to sequential from 7500.

Please also update the filename.

2024-03-13 23:49 UTC, abcoathup commented on ERCS/erc-xxxx.md
> +discussions-to: https://ethereum-magicians.org/t/add-erc-request-method-types/19183
```suggestion
discussions-to: https://ethereum-magicians.org/t/erc-7654-request-method-types/19183
```

2024-05-29 18:25 UTC, SamWilsn requested changes

2024-05-29 18:25 UTC, SamWilsn commented on ERCS/erc-7654.md
> +- RESTful: It can adopt RESTful design principles to make it more predictable and make calls to all parties clearer and easier to understand.
Very little of your Motivation is specific to HTTP-style verbs, and can equally be applied to _any_ standard interface for contracts. You should be trying to convince the reader that contracts should implement specifically `GET`/`POST`/etc., not why we need standards generally.

2024-05-29 18:25 UTC, SamWilsn commented on ERCS/erc-7654.md
> +```
Most of your Rationale reads like implementation hints, and less like the reasoning behind your design decisions. The Rationale section is supposed to explain technical choices you made within the document.

2024-05-29 18:25 UTC, SamWilsn commented on assets/erc-7654/RequestMethodTypes.sol
> +// SPDX-License-Identifier: GPL-3.0
We cannot allow GPL code in reference implementations. That would mean anyone writing code based on your example would also need to be GPL.

If you have the permission of the copyright holder, please relicense this under CC0-1.0 (preferably) or something like MIT or Apache.

2024-06-10 19:39 UTC, SamWilsn commented on ERCS/erc-7654.md
> +Usually each abi file corresponds to a specific contract, and the client cannot use the same abi to call different functions of different contracts. Contract Request Methods redefines the request met
What is an ABI file? Is it defined by an EIP/ERC? If so, you should link to it. If not, can you explain your proposal without comparing it to an ABI file?

2024-06-10 19:39 UTC, SamWilsn commented on ERCS/erc-7654.md
> +Usually each abi file corresponds to a specific contract, and the client cannot use the same abi to call different functions of different contracts. Contract Request Methods redefines the request met
Now you've completely removed any mention of `GET`/`POST`/etc. from your abstract. If you're proposal is centred around these verbs, they probably deserve a mention here.

For context (from [EIP-1](https://eips.ethereum.org/EIPS/eip-1)):

> Abstract is a multi-sentence (short paragraph) technical summary. This should be a very terse and human-readable version of the specification section. Someone should be able to read only the abstract to get the gist of what this specification does.

2024-06-10 19:39 UTC, SamWilsn commented on ERCS/erc-7654.md
> +Usually each abi file corresponds to a specific contract, and the client cannot use the same abi to call different functions of different contracts. Contract Request Methods redefines the request met
The first two sentences are the same as your abstract. Copy-paste error?

2024-06-10 19:39 UTC, SamWilsn commented on ERCS/erc-7654.md
> +4. Encode request parameters and call ```get```, ```pot```, and ```put```.
pot?

2024-06-10 19:39 UTC, SamWilsn commented on ERCS/erc-7654.md
> +### Type of request method ###
```suggestion
### Type of request method
```

2024-06-10 19:39 UTC, SamWilsn commented on ERCS/erc-7654.md
> +### Request method parameter type ###
```suggestion
### Request method parameter type
```

2024-06-11 12:32 UTC, HelloRickey commented
Hey @SamWilsn Thanks again for your patience, please check again.

2024-06-11 14:27 UTC, SamWilsn approved these changes

2024-06-11 14:28 UTC, merged