Add ERC: Token with Metadata
ethereum/ERCs pull request #506
Opened 2024-06-24 16:05 UTC by fewwwww

2024-06-25 00:20 UTC, 18211308 approved these changes

2024-06-25 04:42 UTC, abcoathup commented on ERCS/erc-x.md
> +eip: TBD
```suggestion
eip: 7729
```
Assigning next sequential EIP/ERC/RIP number.

Please also update the filename.

2024-06-25 04:43 UTC, abcoathup commented on ERCS/erc-x.md
> +discussions-to: TBD
Please create a discussions topic in Eth Magicians with a link back to this PR

2024-08-27 21:12 UTC, SamWilsn requested changes

2024-08-27 21:12 UTC, SamWilsn commented on ERCS/erc-7729.md
> +discussions-to: TBD
Still needs a discussion thread.

2024-10-14 15:28 UTC, SamWilsn approved these changes

2024-10-14 15:29 UTC, merged