Add ERC: Vulnerability and Exposure Identifier Specification and Indexing
ethereum/ERCs pull request #513
Opened 2024-06-30 09:31 UTC by dimitrysuen

To address the absence of a standardized reference method for vulnerabilities and to reduce communication costs between protocol developers and ethical hackers, this ERC proposes a rule for creating unique identifiers for vulnerabilities. The aim is to establish a common language in these scenarios.

2024-07-02 02:28 UTC, abcoathup commented on ERCS/erc-tbd.md
> +number: TBD
```suggestion
eip: 7731
```
Assigning next sequential EIP/ERC/RIP number.

Please also update the filename.

2024-07-02 02:28 UTC, abcoathup commented on ERCS/erc-tbd.md
> +discussions-to: TBD
Please create a discussions topic in Eth Magicians with a link to this PR.

2024-07-02 02:29 UTC, abcoathup commented on ERCS/erc-tbd.md
> +title: Vulnerability and Exposure Identifier Specification and Indexing
```suggestion
title: Vulnerability and Exposure Identifier
```
Specification seems superfluous in an ERC title.

2024-07-03 01:06 UTC, abcoathup commented on ERCS/erc-tbd.md
> +created: 2024-05-18
```suggestion
created: 2024-06-30
```
PR was created June 30 (or 29 depending on timezone).

2024-08-29 15:27 UTC, SamWilsn commented on ERCS/erc-7731.md
> +This EIP can benefit the following parties:
```suggestion
This proposal can benefit the following parties:
```

2024-08-29 15:27 UTC, SamWilsn commented on ERCS/erc-7731.md
> +The identifier of vulnerability and exposure MUST conform to the following format: `Database Prefix + Year + Arbitrary Digits`.
This is a somewhat ambiguous way of specifying the parts. Are the pluses literal or are they a concatenation operator?

The way you write it later is much better, so how about something like this:

```suggestion
The identifier of vulnerability and exposure SHALL contain three components separated by hyphens (`‐`) in the following order: database prefix, year, and arbitrary digits. An example of this format is `CVE-2024-0097`, where `CVE` is the database prefix, `2024` is the year, and `0097` are the arbitrary digits.
```

2024-08-29 15:27 UTC, SamWilsn commented on ERCS/erc-7731.md
> +`Database Prefix` SHOULD be uniquely named by different assigners.
This is not really an actionable requirement. Does this mean each assigner should choose exactly one unique prefix? What happens if they don't?

2024-08-29 15:27 UTC, SamWilsn commented on ERCS/erc-7731.md
> +These three parts MUST be connected by `-`, for example, `CVE-2024-0097`. The length of the identifier MUST NOT exceed 32 bytes.
> exceed 32 bytes

This leaves the encoding of the identifier unspecified. Is it UTF-8? ASCII?

2024-08-29 15:27 UTC, SamWilsn commented on ERCS/erc-7731.md
> +`Arbitrary Digits` is RECOMMENDED to start from `0001` and increase incrementally.
What is permitted as a digit? Is Ⅷ (U+2167) a valid digit?

2024-08-29 15:27 UTC, SamWilsn commented on ERCS/erc-7731.md
> +`reportCid` MUST be the vulnerability report's IPFS CID(Content Identifier).
```suggestion
`reportCid` MUST be the vulnerability report's IPFS Content Identifier (CID).
```

2024-08-29 15:27 UTC, SamWilsn commented on assets/erc-7731/veId-and-refVeId.png
We prefer SVG images where possible. If you can't, this PNG is fine.

2024-09-27 07:41 UTC, Mikhai56 requested changes
ERCS/erc-7731.md

2024-09-27 07:46 UTC, Mikhai56 requested changes
assets/erc-7731/veId-and-refVeId.png

2024-12-12 18:29 UTC, chaals commented on ERCS/erc-7731.md
> +`Arbitrary Digits` is RECOMMENDED to start from `0001` and increase incrementally.
Suggest `[0-9]*`

2024-12-13 12:08 UTC, chaals commented on ERCS/erc-7731.md
> +`Arbitrary Digits` is RECOMMENDED to start from `0001` and increase incrementally.
The veid scheme seems heavily optimised for people who produce atomic notices of vulnerabilities, but I'm looking to provide identifiers for items in a specification that is revised and published as a new version from time to time (so far we have worked on a "12-18 months" revision cycle, but it fundamentally depends on how fast things change in the ecosystem).

How do we increase incrementally? We have a set of vulnerabilities that are taken from something that should be used directly as its own reference that already uses the relevant format (Solidity compiler bugs), plus about twice as many other vulnerabilities that are divided across a couple of different dimensions.

Thinking about how to identify these helpfully, it seems like a bad idea to start from 0001 and increment by 1 for each subsequent item in document order. It would be helpful if ethtrust-2023-0021 refers to the same thing as ethtrust-2025-0021 if they are identical in the two specifications. 

One possible approach would be to add identifiers to each requirement, and then maintain the same identifier unless the requirement changes. But if we did this, I would suggest incrementing with every new requirement, so that if we make a smaller change to the requirement that was say ethtrust-2025-0026, we know that we can identify the updated requirement as ethtrust-2028-0026.

2025-03-11 10:18 UTC, closed without merging