review comments
ethereum/ERCs pull request #52
Opened 2023-10-27 18:26 UTC by Joeysantoro

Addresses comments from https://ethereum-magicians.org/t/eip-7540-asynchronous-erc-4626-tokenized-vaults/16153 and transitions the EIP to `Review` status

2023-10-27 18:51 UTC, hieronx approved these changes

2023-10-27 20:16 UTC, Pandapip1 commented
@eth-bot rerun

2023-11-13 16:52 UTC, Joeysantoro commented on ERCS/erc-7540.md
>  author: Jeroen Offerijns (@hieronx), Alina Sinelnikova (@ilinzweilin), Vikram Arun (@vikramarun), Joey Santoro (@joeysantoro)
```suggestion
author: Jeroen Offerijns (@hieronx), Alina Sinelnikova (@ilinzweilin), Vikram Arun (@vikramarun), Joey Santoro (@joeysantoro), Farhaan Ali (@0xfarhaan)
```

2023-11-14 15:36 UTC, SamWilsn approved these changes
Some mixed capitalization in your definitions section bullets.

2023-11-14 17:31 UTC, Pandapip1 requested changes
Due to a temporary kludge the links cannot be updated

2023-11-14 17:31 UTC, Pandapip1 commented on ERCS/erc-7540.md
> +[ERC-7540 Vaults](./erc-7540.md) MUST implement one or both of asynchronous deposit and redemption Request flows. If either flow is not implemented in a Request pattern, it MUST use the ERC-4626 stan
```suggestion
[ERC-7540 Vaults](./eip-7540.md) MUST implement one or both of asynchronous deposit and redemption Request flows. If either flow is not implemented in a Request pattern, it MUST use the ERC-4626 standard synchronous interaction pattern. 
```

2023-11-14 17:31 UTC, Pandapip1 commented on ERCS/erc-7540.md
> +The async pending claims represent a sort of semi-fungible intermediate share class. Vaults can elect to wrap these claims in any token standard they like, for example ERC-20, [ERC-1155](./erc-1155.m
```suggestion
The async pending claims represent a sort of semi-fungible intermediate share class. Vaults can elect to wrap these claims in any token standard they like, for example ERC-20, [ERC-1155](./eip-1155.md) or ERC-721 depending on the use case. This is intentionally left out of the spec to provide flexibility to implementers.
```

2023-11-15 15:41 UTC, Pandapip1 approved these changes

2023-11-15 15:42 UTC, merged