Add ERC : Decentralized Employment System
ethereum/ERCs pull request #573
Opened 2024-08-04 13:59 UTC by jamesavechives

When opening a pull request to submit a new EIP, please use the suggested template: https://github.com/ethereum/EIPs/blob/master/eip-template.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing draft PRs.
 - The build passes.
 - Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

2024-08-05 04:41 UTC, abcoathup commented on ERCS/erc-0000.md
> +eip: 0000
```suggestion
eip: 7750
```
Assigning next sequential EIP/ERC/RIP number.

Please also update the filename.

2024-08-05 04:44 UTC, abcoathup commented on ERCS/erc-0000.md
> +discussions-to: https://ethereum-magicians.org/t/discussion-on-eip-xxx-decentralized-employment-system-des/20578
Please create a topic in Eth Magicians, it can just contain a link to this PR.

2024-08-14 11:38 UTC, Tara-annison commented
Just my view but this feels more like an app layer design/implementation than a core protocol design/implementation.

2024-09-27 19:32 UTC, SamWilsn requested changes

2024-09-27 19:32 UTC, SamWilsn commented on ERCS/erc-7750.md
> +description: A blockchain-based employment system that records employment history.
```suggestion
description: An employment system that records employment history.
```

Almost all ERCs are blockchain-based, so mentioning it here takes up valuable space in your description. You should use more of the available space here to describe your proposal.

2024-09-27 19:32 UTC, SamWilsn commented on ERCS/erc-7750.md
> +2. **Public Reviews**: Reviews are public and accessible to all users, fostering accountability and trust in the system.
You're kind of describing your desired outcome without giving any specific technical instructions to implementers. How will someone know how to represent a review stored on-chain? What functions need to be called? What contracts does the system use?

This is way too vague, even for a draft.

2024-09-27 19:32 UTC, SamWilsn commented on ERCS/erc-7750.md
> +The DES is designed to create a fair, transparent, and secure employment ecosystem. By recording employment history on-chain, automating contract enforcement, and providing a public review system, DE
You're justifying the entire proposal here. This section should, instead, be used to explain technical choices made within the document itself.

2024-09-27 19:32 UTC, SamWilsn commented on ERCS/erc-7750.md
> +4. **Employment Termination**: Test the conditions for employee termination and the associated smart contract enforcement.
Test cases should be a simple set of inputs and expected outputs/states.

2024-09-27 19:32 UTC, SamWilsn commented on ERCS/erc-7750.md
> +James Savechives is a blockchain enthusiast and developer with a keen interest in digital assets and their innovative applications. With a background in software development, James is currently worki
```suggestion
```

This isn't relevant to the specification.

2024-11-29 14:34 UTC, SamWilsn reviewed
The biggest blocker for getting this one merged is that the specification section is too informal and lacking in detail.

2024-11-29 14:34 UTC, SamWilsn commented on ERCS/erc-7750.md
> +2. **Public Reviews**: Reviews can be accessed using `getReviews(uint contractId)`, which returns an array of reviews associated with a specific contract. These reviews contribute to a reputation sco
Generally ERCs propose a complete solidity interface, then explain the function/behaviour of its functions. While it isn't a strict requirement, I'd like to see it here.

2024-11-29 14:34 UTC, SamWilsn commented on ERCS/erc-7750.md
> +2. **Company Profile**: The company profile includes details like name, industry, and a list of registered employees.
These requirements are too vague. How does a user register a new company? How is the profile stored/retrieved? What's the API for these actions?

2024-11-29 14:34 UTC, SamWilsn commented on ERCS/erc-7750.md
> +1. **Contract Creation**: Once the company has tested the employee and is ready to move forward with the final hiring stage, companies can create a labor contract by calling the `createContract(uint
In which contract is the `createContract` function defined?

Also, side note, but calling it a contract may be confusing unless an employment contract is also a smart contract. Maybe employment record?

2024-11-29 14:34 UTC, SamWilsn commented on ERCS/erc-7750.md
> +1. **Contract Creation**: Once the company has tested the employee and is ready to move forward with the final hiring stage, companies can create a labor contract by calling the `createContract(uint
> stores it in a `contracts` mapping, associating each contract with a `companyId`

This is an implementation detail. ERCs should only specify the externally visible behaviour of a contract, not how the contract is implemented.

2024-11-29 14:34 UTC, SamWilsn commented on ERCS/erc-7750.md
> +   - The employee will handle their **employee token** (minted prior to employment) to the company, and the company will review the token's employment history before proceeding with the contract.
What kind of token is this? ERC-721? A soulbound token?

2024-12-31 18:27 UTC, SamWilsn approved these changes

2024-12-31 18:28 UTC, merged