Add ERC: Soulbound Degradable Governance
ethereum/ERCs pull request #674
Opened 2024-10-14 23:11 UTC by 0xneves

This proposal introduces the Soulbound Degradable Governance (SDG), offering a unique solution to common governance challenges in early-stage DAOs by addressing the imbalance between economic and political power, splitting the two forces into two separate tokens.

2024-10-15 23:19 UTC, abcoathup commented on ERCS/erc-TBA.md
> +---
```suggestion
---
eip: 7787
```
Assigning next sequential EIP/ERC/RIP number.

Please also update the filename.

2024-10-15 23:21 UTC, abcoathup commented on ERCS/erc-TBA.md
> +discussions-to: https://ethereum-magicians.org/t/soulbounded-degradable-governance-sdg-a-new-approach-to-dao-power-structures/21326
```suggestion
discussions-to: https://ethereum-magicians.org/t/erc-7787-soulbound-degradable-governance/21326
```
I updated the Eth Magicians title to add in the ERC number and match the title of the ERC

2024-10-15 23:22 UTC, abcoathup commented on ERCS/erc-TBA.md
> +  A governance standard for DAOs where voting power is non-transferable and decays over time without
```suggestion
  DAO governance where voting power is non-transferable and decays over time without
```
Standard is superfluous in the description of an ERC.

2024-10-16 04:19 UTC, 0xneves commented
Getting a lot of errors from EIP Walidator after changing file name 🤔

2024-10-16 04:21 UTC, abcoathup commented on ERCS/erc-7787.md
> +author: Guilherme Neves (@0xneves) Rafael Castaneda (@castacrypto)
```suggestion
author: Guilherme Neves (@0xneves), Rafael Castaneda (@castacrypto)
```

2024-10-16 04:36 UTC, 0xneves commented on ERCS/erc-7787.md
> +author: Guilherme Neves (@0xneves) Rafael Castaneda (@castacrypto)
Thank you @abcoathup

2024-10-29 14:37 UTC, SamWilsn requested changes

2024-10-29 14:37 UTC, SamWilsn commented on ERCS/erc-7787.md
> +1. The political power token SHOULD be non-transferable with over time decayment and MUST implement SDG.
> [...] implement SDG.

This is vague. Is "SDG" an interface?

2024-10-29 14:37 UTC, SamWilsn commented on ERCS/erc-7787.md
> +---
```suggestion
requires: 20
---
```

2024-10-29 14:37 UTC, SamWilsn commented on ERCS/erc-7787.md
> +3. Utilize the `_setVotingUnits(...)` internal function of SDG on the parent contract to set the voting power of addresses when minting, burning or other applying other format of distribution/destruc
If a function is internal, it shouldn't appear in an ERC/EIP. Just describe the observable behaviour (like what would happen if you called the function.)

2024-12-10 16:28 UTC, SamWilsn submitted a review, later dismissed
This is fine for a Draft, but do think about the points I'm raising here.

2024-12-10 16:28 UTC, SamWilsn commented on ERCS/erc-7787.md
> +1. Override the `transfer(...)` function for the governance token to block transfers between addresses.
It is unclear whether the "governance token" here refers to the "political power" token or the "economic power" token. I'd guess that it's political, but it's better to be clear.

2024-12-10 16:28 UTC, SamWilsn commented on ERCS/erc-7787.md
> +
```suggestion
```

2024-12-10 16:28 UTC, SamWilsn commented on ERCS/erc-7787.md
> +No security concerns were found.
```suggestion
No security concerns were found. <!-- TODO -->
```

There will absolutely be security issues here. Think about stuff like what happens if a bound account is compromised. Is the DAO just screwed?

2024-12-10 16:29 UTC, SamWilsn approved these changes

2024-12-10 16:39 UTC, merged